title: Segment-Lidar Documentation
description: Documentation for segment-lidar package.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Anass Yarroudh
repo_url: 'https://github.com/Yarroudh/segment-lidar'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
